ALTER TABLE scores ADD COLUMN player_id TEXT;
ALTER TABLE scores ADD COLUMN perfect_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scores ADD COLUMN great_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scores ADD COLUMN good_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scores ADD COLUMN miss_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scores ADD COLUMN high_speed REAL NOT NULL DEFAULT 1;
ALTER TABLE scores ADD COLUMN replay_data TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_scores_player_id ON scores(player_id);
