ALTER TABLE players ADD COLUMN handicap INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN bot_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN bot_tick INTEGER NOT NULL DEFAULT 0;
