CREATE TABLE IF NOT EXISTS rooms (
 code TEXT PRIMARY KEY NOT NULL, host_id TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'waiting', duration INTEGER NOT NULL DEFAULT 60,
 targets INTEGER NOT NULL DEFAULT 4, difficulty TEXT NOT NULL DEFAULT 'normal',
 seed INTEGER NOT NULL, created_at INTEGER NOT NULL, started_at INTEGER, ends_at INTEGER
);
CREATE TABLE IF NOT EXISTS players (
 id TEXT PRIMARY KEY NOT NULL, room_code TEXT NOT NULL REFERENCES rooms(code),
 name TEXT NOT NULL, score INTEGER NOT NULL DEFAULT 0, combo INTEGER NOT NULL DEFAULT 0,
 best_combo INTEGER NOT NULL DEFAULT 0, current_round INTEGER NOT NULL DEFAULT 0,
 pressed TEXT NOT NULL DEFAULT '[]', mistakes INTEGER NOT NULL DEFAULT 0,
 perfects INTEGER NOT NULL DEFAULT 0, joined_at INTEGER NOT NULL, last_seen INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
 id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
 room_code TEXT NOT NULL REFERENCES rooms(code), player_id TEXT NOT NULL,
 name TEXT NOT NULL, body TEXT NOT NULL, created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS players_room ON players(room_code);
CREATE INDEX IF NOT EXISTS messages_room ON messages(room_code,id);
